---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: redshift_package_name is not defined


- name: Install redshift
  become: true
  package: 
    name: "{{ redshift_package_name }}"
    state: present

- name: Enable and start reshift systemd service
  systemd:
    name: "{{ redshift_service_name }}"
    state: started
    enabled: yes
    scope: user
