---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: cups_package_name is not defined


- name: Install cups
  become: true
  package: 
    name: "{{ cups_package_name }}"
    state: present

- name: Enable and start cups systemd service
  become: true
  systemd:
    name: "{{ cups_service_name }}"
    enabled: yes
