---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: castget_package_name is not defined

- name: Install castget
  become: true
  package: 
    name: "{{ castget_package_name }}"
    state: present

- name: Create music directory
  file:
    path: "{{ ansible_env.HOME }}/music/podcasts"
    state: directory
    mode: 0755

- name: Create podcast directories
  file:
    path: "{{ ansible_env.HOME }}/music/podcasts/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ castget_folders }}"
    
- name: Copy castget systemd config
  become: true
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
  with_items:
    - castget.service
    - castget.timer

- name: Enable and start castget systemd service
  systemd:
    name: "{{ castget_service_name }}"
    enabled: yes
    user: yes

- name: Enable and start castget systemd timer
  systemd:
    name: "{{ castget_service_name }}.timer"
    enabled: yes
    state: started
    user: yes
