---
- name: Install ccid
  become: true
  package: 
    name: ccid
    state: present

- name: Copy nitrokey configuration
  become: true
  copy:
    src: "{{ role_path }}/files/41-nitrokey.rules"
    dest:  /etc/udev/rules.d/41-nitrokey.rules
    owner: root
    group: root
    mode: 0644

- name: Restart systemd-udevd
  become: true
  systemd:
    name: systemd-udevd
    state: restarted

