---
- name: Add Docker Common Repository
  become: true
  yum_repository:
    name: virt7-docker-common-release
    description: Virt7 Docker Common
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    baseurl: http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/

- name: Install Kubernetes packages
  become: true
  package: name={{ item }}
  with_items: 
    - kubernetes
    - etcd
    - flannel

- name: Copy /etc/kubernetes/config
  become: true
  template:
    src: templates/etc/kubernetes/config.j2
    dest: /etc/kubernetes/config

- name: Copy /etc/etcd/etcd.conf 
  become: true
  template:
    src: templates/etc/etcd/etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    # when: is_master == "true"

- name: Copy /etc/kubernetes/apiserver
  become: true
  template:
    src: templates/etc/kubernetes/apiserver.j2
    dest: /etc/kubernetes/apiserver
    # when: is_master == "true"

- name: Start etcd
  become: true
  service: name=etcd state=started enabled=true
  # when: is_master == "true"

  # - name: Make etcd directory
  # command: etcdctl mkdir /kube-centos/network
  # when: is_master == "true"

- name: Make etcd network configuration
  command: 'etcdctl set /kube-centos/network/config "{ \"Network\": \"172.30.0.0/16\", \"SubnetLen\": 24, \"Backend\": { \"Type\": \"vxlan\" } }"'
  # when: is_master == "true"

- name: Start Kubernetes Services
  become: true
  service: name={{ item }} state=started enabled=true
  with_items: 
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - flanneld
    # when: is_master == "true"

- name: Copy /etc/kubernetes/kubelet
  become: true
  template:
    src: templates/etc/kubernetes/kubelet.j2
    dest: /etc/kubernetes/kubelet

- name: Copy /etc/sysconfig/flanneld
  become: true
  template:
    src: templates/etc/sysconfig/flanneld.j2
    dest: /etc/sysconfig/flanneld

- name: Start Kubernetes Services
  become: true
  service: name={{ item }} state=started enabled=true
  with_items: 
    - kube-proxy
    - kubelet
    - flanneld
    - docker

- name: Set the default Kubernetes cluster
  command: kubectl config set-cluster default-cluster --server=http://10.0.2.15:8080

- name: Set the default Kubernetes context
  command: kubectl config set-context default-context --cluster=default-cluster --user=default-admin

- name: Specify the Kubernetes context to use
  command: kubectl config use-context default-context
