---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: mpd_package_name is not defined

- name: Install mpd
  become: true
  package: 
    name: "{{ mpd_package_name }}"
    state: present

- name: Enable and start mpd systemd service
  systemd:
    name: "{{ mpd_service_name }}"
    enabled: yes
    scope: user

- name: Create music directory
  file:
    path: "{{ ansible_env.HOME }}/music"
    state: directory
    mode: 0755
