- name: full system upgrade
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install aur packages
  aur:
    name: "{{ item }}"
    user: "{{ ansible_env.USER }}"
  with_items:
    - apache-tools
    - apachedirectorystudio
    - cnijfilter2-mg7700
    - cower
    - dwm
    - get_iplayer
    - google-chrome
    - id3
    - kubectl-bin
    - ledger-live-bin
    - minify
    - mist
    - rtv
    - st-solarized
    - skypeforlinux-stable-bin
    - spotify
    - st-solarized
    - tor-browser
    - wee-slack
    - urlview
    - zoom
    - openvpn-reconnect

- name: Set timezone to Europe/London
  become: true
  timezone:
    name: Europe/London

- name: Set locale to en_GB.utf8
  become: true
  command: localectl set-locale LANG=en_GB.utf8

# Bug with with_items and include_role so being verbose..
# https://github.com/ansible/ansible/issues/21285
#
- name: Install awscli
  include_role:
    name: awscli

- name: Install cups
  include_role:
    name: cups

    #- name: Install docker
    # include_role:
    #name: docker

- name: Install go
  include_role:
    name: go

- name: Install iptables
  include_role:
    name: iptables

- name: Install motd
  include_role:
    name: motd

- name: Install mpd
  include_role:
    name: mpd

- name: Install castget
  include_role:
    name: castget

- name: Install newsboat
  include_role:
    name: newsboat

- name: Install ntp
  include_role:
    name: ntp

    #- name: Install openssh-server
    #include_role:
    #name: openssh-server

- name: Install redshift
  include_role:
    name: redshift

- name: Install isync
  include_role:
    name: isync

- name: Install bluez
  include_role:
    name: bluez

- name: Install dnsmasq
  include_role:
    name: dnsmasq

- name: Install dnscrypt-proxy
  include_role:
    name: dnscrypt-proxy

- name: Install nitrokey 
  include_role:
    name: nitrokey

- name: Install xorg 
  include_role:
    name: xorg

- name: Install msmtp 
  include_role:
    name: msmtp

- name: Install packages
  become: true
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - acpi
    - alsa-utils
    - arandr
    - bc
    - bzip2
    - coreutils
    - ctags
    - curl
    - dwm
    - dia
    - firefox
    - feh
    - git
    - htop
    - hugo
    - id3
    - jq
    - khal
    - mpv
    - mpc
    - mupdf
    - mutt
    - openvpn
    - namcap
    - notmuch
    - nodejs
    - npm
    - optipng
    - pass
    - pass-otp
    - pandoc
    - pavucontrol
    - pwgen
    - pulseaudio
    - pulseaudio-bluetooth
    - python
    - rsync
    - scrot
    - slock
    - solidity
    - speedtest-cli
    - surfraw
    - ruby
    - traceroute
    - terraform
    - tig
    - tmux
    - tree
    - ttf-liberation
    - unzip
    - virtualbox
    - vagrant
    - vault
    - vim
    - w3m
    - weechat
    - wget
    - wpa_supplicant
    - wireshark-cli
    - wireshark-qt
    - xautolock
    - xf86-video-intel
    - xorg-server
    - xorg-xbacklight
    - xorg-xinit
    - xorg-xsetroot
    - youtube-dl
    - zsh

- name: Allow wheel to sudo with no password
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
