---
- name: Install msmtp
  become: true
  package: 
    name: msmtp
    state: present

- name: Copy msmtpq scripts
  become: true
  copy:
    src: "{{ item }}"
    dest:  /usr/local/bin/
    owner: root
    group: root
    mode: 0755
  with_fileglob:
    - /usr/share/doc/msmtp/msmtpqueue/*

- name: Copy msmtpq systemd config
  become: true
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
  with_items:
    - msmtpq.service
    - msmtpq.timer

- name: Enable and start msmtpq systemd service
  systemd:
    name: msmtpq
    enabled: yes
    scope: user

- name: Enable and start msmtpq systemd timer
  systemd:
    name: msmtpq.timer
    enabled: yes
    state: started
    scope: user
