castget_package_name: castget
castget_service_name: castget
castget_folders: 
- blockchain-insider
- datatransmission
- drumcode
- expansion
- hospital
- johnb
- metalheadz
- resident
- rinsefm
- solid-steel
- shogun-audio
- tms
- this-american-life
- whitenoise
- ukf
- zero-knowledge
