---
- name: Install dnsmasq
  become: true
  package: 
    name: dnsmasq
    state: present

- name: Copy dnsmasq configuration
  become: true
  copy:
    src: "{{ role_path }}/files/dnsmasq.conf"
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644

- name: Enable and start dnsmasq systemd service
  become: true
  systemd:
    name: dnsmasq
    enabled: yes
    state: started

