---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: ccid_package_name is not defined

- name: Install ccid
  become: true
  package: 
    name: "{{ ccid_package_name }}"
    state: present

- name: Install opensc
  become: true
  package: 
    name: "{{ opensc_package_name }}"
    state: present

- name: Enable and start pcscd systemd service
  become: true
  systemd:
    name: "{{ opensc_service_name }}"
    enabled: yes
    state: started

