---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: bluez_package_name is not defined


- name: Install bluez
  become: true
  package: 
    name: "{{ bluez_package_name }}"
    state: present

- name: Install bluez-utils
  become: true
  package: 
    name: "{{ bluez_utils_package_name }}"
    state: present

- name: Install bluez-libs
  become: true
  package: 
    name: bluez-libs
    state: present

- name: Enable and start bluetooth systemd service
  become: true
  systemd:
    name: "{{ bluez_service_name }}"
    enabled: yes
    state: started
