---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"
  when: newsboat_package_name is not defined

- name: Install newsboat
  become: true
  package: 
    name: "{{ newsboat_package_name }}"
    state: present

- name: Copy castget systemd config
  become: true
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
  with_items:
    - newsboat.service
    - newsboat.timer

- name: Enable and start newsboat systemd service
  systemd:
    name: "{{ newsboat_service_name }}"
    enabled: yes
    user: yes

- name: Enable and start newsboat systemd timer
  systemd:
    name: "{{ newsboat_service_name }}.timer"
    enabled: yes
    state: started
    user: yes
